name: Tag CI

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    name: Build and push Docker image on pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Set projeqtor version
        run: echo "PROJEQTOR_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          build-args: |
            PJT_VERSION=$PROJEQTOR_VERSION
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/projeqtor:$PROJEQTOR_VERSION